PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/04128b45701f6ebc25bff9f3f8caa9442d2856be

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/7b36108b548642f1a8513dcf00eb4913f8558ccf) in current PX4/master (f2eefb4e7afd6b384386a1fe2493624263e258df)
https://github.com/PX4/NuttX/compare/7b36108b548642f1a8513dcf00eb4913f8558ccf...04128b45701f6ebc25bff9f3f8caa9442d2856be

04128b4570 (HEAD, origin/master) arch/sim/src: Rename board_lcd.c to up_lcd.c like other sim code
3cb259daa6 drivers/Kconfig:  Move if/endif to subfolder Kconfig
fa3e66fe82 arch/sim/src/:  Reimplement sim uart on top of serial driver framework
6d69439f58 Call xxx_timer_initialize from clock subsystem
76bbed07a4 Call up_irqinitialize from irq subsystem
48f1793a60 tools/testbuild.sh: make sure fail get the real return error value
a8de37fbec Ensure all source code end with one and only one newline
81f1133174 ELF64 support (#220)
e21c30cf9d arch/arm/include/stm32f010g0/chip.h: correct wrong #if defined to fix build break (#227)
b35bf20824 drivers/net/telnet.c:  Run file changed in last PR through nxstyle.

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/c8dbd59e9a8f2f7c9bb4391a32fda01b409059e2

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/91b6ad6a0d00ac107088b18588cd54d40e3cb796) in current PX4/master (f2eefb4e7afd6b384386a1fe2493624263e258df)
https://github.com/PX4/NuttX-apps/compare/91b6ad6a0d00ac107088b18588cd54d40e3cb796...c8dbd59e9a8f2f7c9bb4391a32fda01b409059e2

c8dbd59e (HEAD -> master, origin/master) netutils/telnetd/telnetd_daemon.c: Avoid a warning if CONFIG_NET_SOCKOPTS=n
d2522e28 apps/netutils/telnetd:  Fix undefined reference to setsockopt.
f14aead5 Shouldn't use local readline in telnet
960a92c6 (origin/master_nxp_drone_boards) Make SO_REUSEADDR not mandatory in netlib
a5dff52a Change unimplemented requests behaviour in gs2200m
2f4b309b gs2200m: Retry indefinately on GS2200M_IOC_ASSOC failure
e738fbed graphics/littlevgl/Makefile: update lvgl.h dependency to fix parallel build break
bb3cd0a4 apps: elf: Fix stack corruption in task test
bf3e6e23 Improvements for telnet server
43a36996 nettest: Avoid conflicts with host definitions